### ISSUE TITLE
GNOME 45 ETA?

### ISSUE THREAD

**Issue by Aqua1ung** [G-dH/vertical-workspaces#111]
Any ETA on V-Shell for GNOME 45? Ever thought of publishing a nightly build for those of us willing to test?

**Comment by G-dH** [comment]
It's easy to install V-Shell directly from the `esm-modules` branch, instructions are in the README on the main page. I will release it on e.g.o. soon hopefully. In any case, testing before release is welcome.

**Comment by stdevPavelmc** [comment]
> It's easy to install V-Shell directly from the `esm-modules` branch, instructions are in the README on the main page. I will release it on e.g.o. soon hopefully. In any case, testing before release is welcome.

Deal, testing and feedback...

**Comment by stdevPavelmc** [comment]
Gnome 45, Ubuntu 23.10, Wayland

So far so good, there is no way to put the dock to the left?

![image](https://github.com/G-dH/vertical-workspaces/assets/42220093/c6ab8656-fc80-4fb0-ba4b-e803542a37de)

I don't find any setting for the dock?

**Comment by stdevPavelmc** [comment]
> @stdevPavelmc: It's _Dash_, not Dock ;) You can also use the predefined profile _GNOME 3_ to set the legacy layout.
> 
> Check whether the _Dash_ module is enabled in the _Modules_ tab of the Settings window.

Got it!

After tweaking some knobs and switches if found that it was another extension moving it down, disabled and now it works as it should, thanks.

**Comment by G-dH** [comment]
@stdevPavelmc  Yeah, now I see that it really was _Dock_ which has its own position settings. Better if you can live without it because `Dash to Dock` extension is supported by the V-Shell but still causes some problems.

**Comment by Aqua1ung** [comment]
Anything still keeping you from releasing this on e-g-o?

**Comment by G-dH** [comment]
@Aqua1ung  Time...

**Comment by Iron-Squid** [comment]
I'm aware of the version for Gnome 45 being accessed via the `esm-modules` branch, but I'd like to let anyone in charge of handling the [Gnome Extensions page](https://extensions.gnome.org/extension/5177/vertical-workspaces/) know that it currently does not reflect Gnome 45 support.

If this is due to the currently supported Gnome 45 version being unstable/unfinished, ignore me. 
If not, now you know.

**Comment by toonarmycaptain** [comment]
I would love to know when this is available in  extensions.gnome.org!

Thankyou for your work :)

**Comment by G-dH** [comment]
Hopefully this week..

**Comment by G-dH** [comment]
I just switched branches:
`main` moved to `gnome-42-44`
`esm-modules` moved to `main`

[Installation instructions updated](https://github.com/G-dH/vertical-workspaces#installation-from-github-repository).

**Comment by G-dH** [comment]
V-Shell v45.1 is finally available on [EGO](https://extensions.gnome.org/extension/5177/vertical-workspaces/)

**Comment by ppareit** [comment]
Thank you!

**Comment by mlmilliman** [comment]
Nice but Version 39 or 45.1 per EGO doesn't seem to work with GNOME 45. It throws up this error: WorkspaceAnimation.MonitorGroup is undefined.

**Comment by G-dH** [comment]
@mlmilliman What GNOME version (the part behind dot is important) and distro are you running? V-Shell 45.1 s compatible with the current GNOME 45.1 but not with 45.0.

**Comment by mlmilliman** [comment]
@G-dH  I'm running GNOME 45.0 because Ubuntu 23.10 still has not released 45.1 in its stable build. I assumed that V-Shell was built for GNOME 45.1 based on the version number. I'd gladly run 45.1 if it was available with my distro. Right now I'm missing the whole app grid when I removed V-Shell, and I'm trying to figure out how to restore it.  I should probably look at your source code for the answer.

**Comment by G-dH** [comment]
@mlmilliman Sorry for that, Ubuntu 23.10 should receive 45.1 soon, until then disable _WorkspaceAnimation_ module in V-Shell Settings.

**Comment by mlmilliman** [comment]
@G-dH This morning I received the update for 45.1 and all is working well again...actually maybe better.
