### ISSUE TITLE
Last used window name in workspace thumbnails labels.

### ISSUE THREAD

**Issue by VBBr** [G-dH/vertical-workspaces#37]
If you created a lot of windows of the same app in different ws's, they will all have the same label. i think its better to put window name instead of app name inside ws label.
![image](https://user-images.githubusercontent.com/70429241/212541795-2f21de92-003c-4aee-8267-df60ae30f15e.png)

**Comment by G-dH** [comment]
I can add the option, but this a task for my [AATWS](https://github.com/G-dH/advanced-alttab-window-switcher) extension. It can work as usual Alt+Tab switcher, dock that can be triggered by hot edge or Super key, offers type to search feature and also full-size previews which can be toggled by secondary click (in default).

Btw, VW now also includes window search provider. You can list all windows from overview by pressing _Space_ key or use secondary click on _Show Apps_ button and you can also use secondary click on window preview which should list all windows of the app (windows with its app name in the description). In all cases you can continue typing to filter the results.

**Comment by VBBr** [comment]
AATWS looks like a good extension but it adds complexity: i have to use some shortcut to open it. probably if you use a lot of shortcuts one additional shortcut wont be problem, but i currently use only two - Super and Super+Scroll Wheel.
Also i like to open books in two windows. For example if i have 4 books opened i will need 4 ws's to organize them. And when i want to switch to another book i will have to choose between 4 ws's. But if i use aatws/space in vw i will see 8 items.
I can set order of ws's and I will know that some book is located somewhere at the bottom/middle/top.
To use search provider i will have to remember all books a have opened. But using ws's i see all their name i can choose between them.

Did i convince you? :)

**Comment by VBBr** [comment]
I also found out that there is index+ws name option. but i cant figure out how to set ws name

**Comment by G-dH** [comment]
Thanks for the explanation, adding the option is not a problem, it's not there just because it seemed useless to me. I'll add it. WS names are being read from gsettings key `/org/gnome/desktop/wm/preferences/workspace-names`. You can use d-conf editor to set them, or some extension. My [Workspace Switcher Manager](https://github.com/G-dH/workspace-switcher-manager) extension allows you to name up to 10 workspaces and also to replace ws switcher popup which can show you the current window title when you switch workspace.

Btw, AATWS allows you to hit bottom/top edge of the monitor to open window switcher which can show you thumbnails of windows on the current monitor (you can immediately use right click to switch filter mode - monitor, workspace, all), scroll switches workspaces updating the switcher, right click on the thumbnail shows you full-screen preview, click on the app icon toggles single app mode, if you start typing, AATWS find your window even if it's out of the scope of the current filter mode. And all this can be also accessible using Alt+Tab, or Super key and you can adjust all controls, content, dimensions, to your needs.

**Comment by VBBr** [comment]
Tried AATWS bottom edge switcher and WSM switcher popup with windows labels. I think current VW with window labels is more simple solution for me. Also it goes along with my idea to mostly rely only on super button.

**Comment by VBBr** [comment]
I see VW getting more and more features recently. I'm a bit worried it will affect performance. It feels like entering overview with super is delayed with VW turned on.

**Comment by G-dH** [comment]
I'm moving key features from my OFP extension into VW because it has overlaps and it's hard to keep them both compatible. These features should not slow down the overview but I'm thinking about splitting VW into modules that can be disabled and enabled easily.
The truth is that I'm experimenting with controlled delay that depends on the number of windows on the active workspace. The reason is performance on slower/loaded systems since building all the windows while entering the overview takes some time and user experience is far better with delayed but smooth animation than with quicker but stuttering animation. I'll add an option to the settings window.

**Comment by G-dH** [comment]
You should be able to test the time needed to build the overview content (exept ws thumbnails):
Open terminal and execute:

    journalctl /usr/bin/gnome-shell -fo cat

Open Looking Glass (Alt+F2, lg, Enter)
In the lg execute following one-liner:

    t=Date.now();Main.overview._overview._controls._workspacesDisplay.prepareToEnterOverview();Main.overview._overview._controls._searchController.prepareToEnterOverview();print(Date.now()-t)

Repeat several times on default Shell and with VW enabled, while the overview is closed. Time in ms should appear in the terminal.
This is the minimal time before the animation to the overview begins. When the animation starts, all the graphical content must be realized and this process causes another delay, but this time the animation is already running, so visually can the animation just skip some initial frames or jump several times or skip all frames on slow system with many open windows. Default animation time is 250 ms.

**Comment by VBBr** [comment]
VW:
  Chrome, extension manager and kgx: ~21
  + 5 evince windows: ~32
  + 7 windows of various apps (no evince windows): ~41
No VW:
  Chrome, extension manager and kgx: ~27
  + 5 evince windows: ~32
  + 7 windows of various apps (no evince windows): ~40
  
I didn't notice that you said to test in **default** shell and with VW enabled. But I guess it's still ok?
Extensions i have besides VW:
legacyschemeautoswitcher@joshimukul29.gmail.com
grand-theft-focus@zalckos.github.com
appindicatorsupport@rgcjonas.gmail.com
bluetooth-quick-connect@bjarosze.gmail.com
espresso@coadmunkee.github.com
date-menu-formatter@marcinjakubowski.github.com
drive-menu@gnome-shell-extensions.gcampax.github.com
