### ISSUE TITLE
The 64px icon-size in the "dash" is too small on 4K

### ISSUE THREAD

**Issue by AriaanBruinsma** [G-dH/vertical-workspaces#43]
I tried the version from Github, because of that I finally learned how to install extensions the CLI-way :P (Gnome's biggest mystery it seems) But unfortunately I saw no difference in the way I've set it up. Also, I'd like to note that the extension didn't became available after a logging the user out and in. (Not described in the instructions on GitHub.)

To summarize what I was hoping for; The 64px icon-size in the "dash" is simply too small on a 4K (27") display, even if I use 200% scaling.

**Comment by AriaanBruinsma** [comment]
I just realized I should have posted it here, I'm not sure if you have the ability to remove messages in the Gnome Extension page, but feel free to remove that one. Didn't wake up yet, sorry. ☕

**Comment by G-dH** [comment]
In the latest version, you can set the icon size to 80, 96, 112 and 128px. If you don't see it in the settings, you probably made a mistake during the installation. Installation instructions are on the main page, you should see version 23.5 in the settings window About page.

    git clone https://github.com/G-dH/vertical-workspaces.git
    cd vertical-workspaces/
    make install

If you already have some version of the extension installed and enabled on your system, the new one will overwrite it and start working after restarting the Shell, otherwise you have to enable it manually (the easiest way is the Extensions app) after restarting the Shell.

**Comment by G-dH** [comment]
Now the latest version should be stable enough for regular use, I would appreciate if you let me know how it works for you.
