### ISSUE TITLE
Quicker way to view applications [FEATURE]

### ISSUE THREAD

**Issue by amwnag** [G-dH/vertical-workspaces#62]
**Is your feature request related to a problem? Please describe.**
Currently, the only touchpad gesture I know of is to 3-finger left swipe twice. Some more options and configurations would be cool.

**Describe the solution you'd like**
Since the 3-finger right swipe is currently unused, I can see it being used for direct application grid access. Alternatively, 4-finger left swipe.

**Describe alternatives you've considered**
It's possible to click on a "show applications" button, but gestures are cool

**Additional context**
Great and essential plugin for me :)

**Comment by G-dH** [comment]
The only thing V-Shell does about gestures is change their orientation and direction according to the current orientation of the workspaces and the position of the workspace thumbnails, otherwise it's the GNOME default. With vertical orientation of workspaces that means the first horizontal 3 finger swipe against ws thumbnails position opens the overview, the second one continues to the app grid. Thanks for the feedback.
