### ISSUE TITLE
[FEATURE] Show workspaces on mouse hovering and show all active apps icons on workspace taskbar 

### ISSUE THREAD

**Issue by dgmaths9** [G-dH/vertical-workspaces#67]
I have been using the workspaces-to-dock extension on Ubuntu 20.04. Though the vertical-workspaces extension is lovely, I am really missing the following two features. It would have been nice to have an option for 

1. Autohide : Show the dock on mouse hover -  when enabled, the dock shows when the mouse touches the right edge of the screen (in vertical workspaces), without pressing the super key. That would make it much easier to see and switch between workspaces.

2. Show workspace taskbar (apps) - When enabled, the workspace taskbar appears in the caption. The taskbar displays the icons of applications running on the workspace. This way we can see all applications running on the current workspace just from the app icons. When the taskbar app icon is left-clicked, the application is brought into focus or minimized if it's already in focus. Application may be dragged from one workspace to another just by moving these icons.

**Comment by G-dH** [comment]
Thanks for the suggestion, but I think the V-Shell can offer more efficient navigation than the icon-cluttered workspace thumbnails. If you don't like unnecessary movement on the display, you can switch the _Overview Mode_ to _Static Workspace_, move the dash and workspace thumbnails to the same side and set the hot corner to _Follow Dash - Hot Edge_. You can also switch windows by scrolling over the dash icons (followed by clicking to confirm the selection) and if you need to see all windows on the workspace, just click the active workspace thumbnail to expose the windows like in the default overview. You can also click on the _Search Open Windows_ icon in the dash (or press Space) to see list of all open windows on all workspaces and filter the list by typing.

**Comment by G-dH** [comment]
> How to enforce an app to open in the current workspace even if it is opened in another workspace?

GNOME Shell has no influence on this behavior, it depends on each application separately.

The first option you have is to open a new window first and then the file, V-Shell has an option to automatically open a new window instead of switching to an existing one if that is on another workspace.

The second option for files opened from a file manager used to be to copy the application launcher from `/usr/share/applications/` to `~/.local/share/applications/` and modify its `Exec:` line so the app will always open a new window (if the app supports this option from the command line), for example the gedit:

`Exec=gedit --new-window %U`
or
`Exec=gedit --standalone %U`

**Comment by dgmaths9** [comment]
Thanks again for suggesting a solution!!
