### ISSUE TITLE
[BUG] Cannot disable slide-up animation of search

### ISSUE THREAD

**Issue by dz4k** [G-dH/vertical-workspaces#74]
**Describe the bug**
When using search, the word "Searching..." slides up all the way from the bottom of the view. In stock GNOME, it simply fades in.

This could be desirable of course, but there's no way to disable it. Furthernore. it doesn't happen when the app grid is open, leading me to believe it's a bug.

Personally, I find it quite distracting. It pulls my eye away from the search bar when I'm trying to use it.

**Basic debug information**
 - Did disabling all other extensions help?
   - No
 - Did you find conflicting extension?
   - No

**To Reproduce**

Search for anything in the workspace preview.

Search for anything in the app grid.

**Expected behavior**
The default animation appears. It's possible to choose the slide up animation, in which case it always appears including in the app grid.

**Screenshots**

**System:**
 - OS: Fedora Silverblue 38
 - Version of V-Shell extension: 29
 - Source of installation: GitHub
 - Other installed and enabled extensions: 
   ```
   > gnome-extensions list
   Always-Show-Titles-In-Overview@gmail.com
   dash-to-dock@micxgx.gmail.com
   dash-to-panel@jderose9.github.com
   dock-from-dash@fthx
   floating-panel@aylur
   gsconnect@andyholmes.github.io
   just-perfection-desktop@just-perfection
   material-you-theme@asubbiah.com
   reorder-workspaces@jer.dev
   rounded-window-corners@yilozt
   space-bar@luchrioh
   static-background@denizaksimsek.com
   trayIconsReloaded@selfmade.pl
   vertical-overview@RensAlthuis.github.com
   Rounded_Corners@lennart-k
   vertical-workspaces@G-dH.github.com
   transparent-top-bar@ftpix.com
   apps-menu@gnome-shell-extensions.gcampax.github.com
   background-logo@fedorahosted.org
   launch-new-instance@gnome-shell-extensions.gcampax.github.com
   places-menu@gnome-shell-extensions.gcampax.github.com
   window-list@gnome-shell-extensions.gcampax.github.com
   
   > gnome-extensions list --enabled
   rounded-window-corners@yilozt
   Rounded_Corners@lennart-k
   vertical-workspaces@G-dH.github.com
   ```

**Comment by G-dH** [comment]
Thanks for the feedback, the search view animation is more of an experiment and can be disabled in the `Animations - Overview` section of the `Behavior` tab. The animation is not just about the `Searching...` banner, the entire search results view is animated and if your system was fast enough, you could see the search results sliding into the screen. The transition was initially linked with the app grid transition and I forgot to remove restriction for the app grid mode, that's a bug. Also the animation of the workspace preview to the thumbnails is so quick to avoid stuttering caused by realizing the search results. I'll try to improve it, in any case the animation is optional as I mentioned before.

**Comment by G-dH** [comment]
The app grid state search view animation has been fixed and improved, available in the repository.
