### ISSUE TITLE
[BUG] Problem with ubuntu dock

### ISSUE THREAD

**Issue by mchalandon** [G-dH/vertical-workspaces#90]
**Describe the bug**
Since the last release, with V-Shell enabled, when the Super key is pressed, (in order to enter in "search" mode), the unbuntu dock (the standard one) disappears. 
The only way to bring it back is to disable and reenable Unbuntu Dock ; then Unbuntu Dock is ok until the Super key is pressed again.

**Basic debug information**
 - Disabling all other extensions didn't help ; with only V-shell and Ubuntu Dock enabled, the problem persists. 
 - Additionnal info : Dash-to-dock is NOT installed

**To Reproduce**
1. Disable all extensions, 
2. Enable Ubuntu Dock and V-Shell
3. Press the Super key
4. The dock disapears and doesn't reapear when Super key is pressed again

**System:**
 - OS: ubuntu 22.04, wayland or xorg (both tested)
 - Version of V-Shell extension: 30
 - Source of installation: extension.gnome.org
 - Other installed and enabled extensions: Ubuntu Dock (integrated)

**Comment by G-dH** [comment]
See #86 Ubuntu Dock is a fork of Dash to Dock.

**Comment by mchalandon** [comment]
ok, I wasn't aware of it, thanks for your reply.

**Comment by npanuhin** [comment]
Hello! I have exactly the same problem:

https://github.com/G-dH/vertical-workspaces/assets/38539949/d2bc10b8-e745-4f39-bd78-0fac47fb5f0b

**Comment by mchalandon** [comment]
Yes, installing the GitHub version is a good temporary  workaround ; 
additionally, before installing, we can edit the metadata.json, with a high value for version, in order to get rid of the auto-update.

**Comment by bmonjoie** [comment]
I don't know if I should open a new bug for this or not but I have an issue with VShell (30) when Ubuntu Dock (79) is enabled.
I'm on Ubuntu 23.04 with a dual screen setup in vanilla Gnome (XOrg) mode.

The problem is that when I log in, there is no overview, everything is broken. The super-key and the hot corner don't work. Clicking on a window don't bring it focus, I have to use alt+tab to switch between windows and I can't logout except by launching `gnome-session-quit` in a terminal.
Disabling VShell doesn't fix the issue until I fully logout and log back in.
When the problem occurs, disabling VShell makes the hot corner and super-key working again but the overview is still completely broken.

The only solution for this I have found so far is to disable VShell using the terminal, logging out, logging back in and enabling VShell after everything is loaded. When VShell is enabled after everything is loaded, I have no issue whatsoever.

I have tried downloading the latest version from github and installing the zip file but the issue remains.
I have also tried to reset all the configuration in VShell but the issue remains.

If I disable Ubuntu Dock, VShell loads just fine when logging in.
Therefore, I assume the problem is similar to this one.

I don't know where to look to give you logs about what is going wrong. The only other information I can give you is that when I had the issue, I enabled/disabled VShell through the extension-manager application launched from a terminal and this is what it told me:
```
(extension-manager:9579): GLib-GObject-CRITICAL **: 10:24:13.773: value "((ExmExtensionState) 8)" of type 'ExmExtensionState' is invalid or out of range for property 'state' of type 'ExmExtensionState'
```

I have no idea if this helps.

Anyway, even though it's a bit annoying, I'm still super grateful for your work and this extension.

**Comment by G-dH** [comment]
@bmonjoie The proper installation of the latest V-Shell is here: [Installation from GitHub repository](https://github.com/G-dH/vertical-workspaces#installation-from-github-repository). Have you tried replacing the Ubuntu Dock with the original Dash to Dock extension?

**Comment by ilejn** [comment]
> @bmonjoie The proper installation of the latest V-Shell is here: [Installation from GitHub repository](https://github.com/G-dH/vertical-workspaces#installation-from-github-repository). Have you tried replacing the Ubuntu Dock with the original Dash to Dock extension?

Installing Dash to Dock works for me on fresh Ubuntu 23.04.
Although I have Ubuntu 22.04 with 22.04, and it is affected by the issue.

**Comment by G-dH** [comment]
Please, try the latest update from the repository and let me know how it works for you.

**Comment by mchalandon** [comment]
> Please, try the latest update from the repository and let me know how it works for you.

it works fine, thank you :+1:

**Comment by bmonjoie** [comment]
Disabling Ubuntu-Dock and installing DtD reverts to the previous behavior: The UI seems broken when logging in but going out and back into expose mode solves the issue.
Therefore, I don't have to disable the extension, log out, log back in, and reenable the extension.

This is, therefore, an acceptable workaround for me. Thanks for the help!

**Comment by G-dH** [comment]
@bmonjoie Every system behaves differently, it's about timing I don't have under control. The only good solution is support from DtD authors, [let them know](https://github.com/micheleg/dash-to-dock/issues/2043).

**Comment by bmonjoie** [comment]
@G-dH I'm very sorry if my comment came across badly. I'm fully aware that you did your best to avoid the conflict with DtD and that the bug I'm experiencing is out of your control. I meant this is a minor inconvenience to me I can live with. 

I am very grateful for this extension, and I greatly appreciate all your efforts to make it as good as it currently is already.

**Comment by G-dH** [comment]
@bmonjoie Don't worry, no bad feelings, it was just information.

**Comment by G-dH** [comment]
The latest V-Shell in the repository should be even more compatible with DtD (the recursion issue) and if you want better experience, you can try my DtD patch - the easiest way is to overwrite the docking.js file in your DtD directory ~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/ with my version:
GS 45: https://github.com/G-dH/dash-to-dock/blob/v-shell-patch/docking.js
GS 40-44: https://github.com/G-dH/dash-to-dock/blob/v-shell-patch-legacy/docking.js

Please, let me know how it works for you. ;)
